/*
 * Vercel API
 *
 * Unnofficial OpenAPI description for the Vercel API
 *
 * API version: 0.1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

// SecretDeletion struct for SecretDeletion
type SecretDeletion struct {
	Uid     string `json:"uid"`
	Name    string `json:"name"`
	Created int64  `json:"created"`
}

// NewSecretDeletion instantiates a new SecretDeletion object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSecretDeletion(uid string, name string, created int64) *SecretDeletion {
	this := SecretDeletion{}
	this.Uid = uid
	this.Name = name
	this.Created = created
	return &this
}

// NewSecretDeletionWithDefaults instantiates a new SecretDeletion object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSecretDeletionWithDefaults() *SecretDeletion {
	this := SecretDeletion{}
	return &this
}

// GetUid returns the Uid field value
func (o *SecretDeletion) GetUid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Uid
}

// GetUidOk returns a tuple with the Uid field value
// and a boolean to check if the value has been set.
func (o *SecretDeletion) GetUidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Uid, true
}

// SetUid sets field value
func (o *SecretDeletion) SetUid(v string) {
	o.Uid = v
}

// GetName returns the Name field value
func (o *SecretDeletion) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *SecretDeletion) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *SecretDeletion) SetName(v string) {
	o.Name = v
}

// GetCreated returns the Created field value
func (o *SecretDeletion) GetCreated() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Created
}

// GetCreatedOk returns a tuple with the Created field value
// and a boolean to check if the value has been set.
func (o *SecretDeletion) GetCreatedOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Created, true
}

// SetCreated sets field value
func (o *SecretDeletion) SetCreated(v int64) {
	o.Created = v
}

func (o SecretDeletion) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["uid"] = o.Uid
	}
	if true {
		toSerialize["name"] = o.Name
	}
	if true {
		toSerialize["created"] = o.Created
	}
	return json.Marshal(toSerialize)
}

type NullableSecretDeletion struct {
	value *SecretDeletion
	isSet bool
}

func (v NullableSecretDeletion) Get() *SecretDeletion {
	return v.value
}

func (v *NullableSecretDeletion) Set(val *SecretDeletion) {
	v.value = val
	v.isSet = true
}

func (v NullableSecretDeletion) IsSet() bool {
	return v.isSet
}

func (v *NullableSecretDeletion) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSecretDeletion(val *SecretDeletion) *NullableSecretDeletion {
	return &NullableSecretDeletion{value: val, isSet: true}
}

func (v NullableSecretDeletion) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSecretDeletion) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
