/*
 * Vercel API
 *
 * Unnofficial OpenAPI description for the Vercel API
 *
 * API version: 0.1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

// AliasInclusion struct for AliasInclusion
type AliasInclusion struct {
	Domain string `json:"domain"`
}

// NewAliasInclusion instantiates a new AliasInclusion object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAliasInclusion(domain string) *AliasInclusion {
	this := AliasInclusion{}
	this.Domain = domain
	return &this
}

// NewAliasInclusionWithDefaults instantiates a new AliasInclusion object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAliasInclusionWithDefaults() *AliasInclusion {
	this := AliasInclusion{}
	return &this
}

// GetDomain returns the Domain field value
func (o *AliasInclusion) GetDomain() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Domain
}

// GetDomainOk returns a tuple with the Domain field value
// and a boolean to check if the value has been set.
func (o *AliasInclusion) GetDomainOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Domain, true
}

// SetDomain sets field value
func (o *AliasInclusion) SetDomain(v string) {
	o.Domain = v
}

func (o AliasInclusion) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["domain"] = o.Domain
	}
	return json.Marshal(toSerialize)
}

type NullableAliasInclusion struct {
	value *AliasInclusion
	isSet bool
}

func (v NullableAliasInclusion) Get() *AliasInclusion {
	return v.value
}

func (v *NullableAliasInclusion) Set(val *AliasInclusion) {
	v.value = val
	v.isSet = true
}

func (v NullableAliasInclusion) IsSet() bool {
	return v.isSet
}

func (v *NullableAliasInclusion) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAliasInclusion(val *AliasInclusion) *NullableAliasInclusion {
	return &NullableAliasInclusion{value: val, isSet: true}
}

func (v NullableAliasInclusion) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAliasInclusion) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
