/*
 * Vercel API
 *
 * Unnofficial OpenAPI description for the Vercel API
 *
 * API version: 0.1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

// SecretValue struct for SecretValue
type SecretValue struct {
	Type *string  `json:"type,omitempty"`
	Data *[]int32 `json:"data,omitempty"`
}

// NewSecretValue instantiates a new SecretValue object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSecretValue() *SecretValue {
	this := SecretValue{}
	return &this
}

// NewSecretValueWithDefaults instantiates a new SecretValue object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSecretValueWithDefaults() *SecretValue {
	this := SecretValue{}
	return &this
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *SecretValue) GetType() string {
	if o == nil || o.Type == nil {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SecretValue) GetTypeOk() (*string, bool) {
	if o == nil || o.Type == nil {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *SecretValue) HasType() bool {
	if o != nil && o.Type != nil {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *SecretValue) SetType(v string) {
	o.Type = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *SecretValue) GetData() []int32 {
	if o == nil || o.Data == nil {
		var ret []int32
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SecretValue) GetDataOk() (*[]int32, bool) {
	if o == nil || o.Data == nil {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *SecretValue) HasData() bool {
	if o != nil && o.Data != nil {
		return true
	}

	return false
}

// SetData gets a reference to the given []int32 and assigns it to the Data field.
func (o *SecretValue) SetData(v []int32) {
	o.Data = &v
}

func (o SecretValue) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	if o.Data != nil {
		toSerialize["data"] = o.Data
	}
	return json.Marshal(toSerialize)
}

type NullableSecretValue struct {
	value *SecretValue
	isSet bool
}

func (v NullableSecretValue) Get() *SecretValue {
	return v.value
}

func (v *NullableSecretValue) Set(val *SecretValue) {
	v.value = val
	v.isSet = true
}

func (v NullableSecretValue) IsSet() bool {
	return v.isSet
}

func (v *NullableSecretValue) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSecretValue(val *SecretValue) *NullableSecretValue {
	return &NullableSecretValue{value: val, isSet: true}
}

func (v NullableSecretValue) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSecretValue) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
