---
name: Acceptance Tests
on:
  push:
    paths:
      - '**.go'
      - '.github/workflows/**'
  pull_request:
    types: ['opened', 'synchronize']
    paths:
      - '**.go'
      - '.github/workflows/**'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false
      - uses: actions/setup-go@v2
        with:
          go-version: '1.15'
      - uses: actions/checkout@v2
    # - run: terraform version
      - run: make testacc
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}